openapi: 3.0.0
info:
  title: Cryptography API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /encrypt:
    post:
      summary: Data Encryption
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        '200':
          description: Encrypted data
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
  /decrypt:
    post:
      summary: Data Decryption
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        '200':
          description: Decrypted data
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
  /sign:
    post:
      summary: Sign Data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        '200':
          description: Signed data
          content:
            application/json:
              schema:
                type: object
                properties:
                  signature:
                    type: string
  /verify:
    post:
      summary: Verify Signature
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                signature:
                  type: string
                data:
                  type: object
                  additionalProperties: true
      responses:
        '204':
          description: Verification successful
        '400':
          description: Invalid signature
