# baseURL
@baseURL = http://localhost:3000

###
# Data Encryption
POST {{ baseURL }}/encrypt
Content-Type: application/json

{
  "key1": "value1",
  "object1": {
    "key2": "value2"
  },
  "object2": {
    "key3": {
      "key4": "value4"
    }
  }
}

###
# Data Decryption
POST {{ baseURL }}/decrypt
Content-Type: application/json

{
  "key1": "dmFsdWUx",
  "object1": "eyJrZXkyIjoidmFsdWUyIn0=",
  "object2": "eyJrZXkzIjp7ImtleTQiOiJ2YWx1ZTQifX0="
}
